---
- name: Update fapolicyd configuration
  hosts: all
  become: true
  gather_facts: false
  vars:
    trusted_apps:
      - path: /home/cloud-user/cowsay
        size: 2772992
        checksum: "fc564f72acb1e84a64131d687ef5106dadcf410d03126638aca46e498d020ca6"
  roles:
    - { role: shaneboulden.fapolicyd }
